const WHATSAPP_NUMBER = "265992282807";
const demoProducts = [
  {id:"lenovo-ideapad-3",name:"Lenovo IdeaPad 3",category:"Laptops",price:485000,description:"A dependable everyday laptop for work, learning and browsing.",availability:"Available",image:"https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80",specifications:{Display:"15.6 inch",Memory:"8GB RAM",Storage:"256GB SSD"}},
  {id:"hp-elitebook",name:"HP EliteBook",category:"Laptops",price:650000,description:"A polished business laptop with a comfortable keyboard and solid performance.",availability:"Available",image:"https://images.unsplash.com/photo-1541807084-5c52b6b3adef?auto=format&fit=crop&w=900&q=80",specifications:{Display:"14 inch",Memory:"8GB RAM",Storage:"256GB SSD"}},
  {id:"samsung-galaxy-a15",name:"Samsung Galaxy A15",category:"Smartphones",price:385000,description:"Bright display, dependable battery and the everyday features you need.",availability:"Available",image:"https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?auto=format&fit=crop&w=900&q=80",specifications:{Display:"6.5 inch",Memory:"4GB RAM",Storage:"128GB"}},
  {id:"honor-x-series",name:"Honor X Series",category:"Smartphones",price:420000,description:"A stylish smartphone made for photos, messages and entertainment.",availability:"Available",image:"https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=900&q=80",specifications:{Display:"6.7 inch",Memory:"8GB RAM",Storage:"128GB"}},
  {id:"nokia-keypad-phone",name:"Nokia Keypad Phone",category:"Keypad Phones",price:65000,description:"Simple, reliable calling with a battery that lasts.",availability:"Available",image:"https://images.unsplash.com/photo-1556035689-4f7f2e4e5f8d?auto=format&fit=crop&w=900&q=80",specifications:{Battery:"Long-lasting",Network:"Dual SIM",Type:"Keypad"}},
  {id:"universal-laptop-charger",name:"Universal Laptop Charger",category:"Laptop Chargers",price:55000,description:"A practical replacement charger for compatible laptops.",availability:"Available",image:"https://images.unsplash.com/photo-1625842268584-8f3296236761?auto=format&fit=crop&w=900&q=80",specifications:{Output:"Multiple tips",Use:"Laptop",Type:"Universal"}},
  {id:"fast-phone-charger",name:"Fast Phone Charger",category:"Phone Chargers",price:28000,description:"A compact charger for dependable daily charging.",availability:"Available",image:"https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=900&q=80",specifications:{Type:"USB charger",Use:"Smartphones",Feature:"Fast charge"}},
  {id:"power-bank-10000",name:"10,000mAh Power Bank",category:"Power Banks",price:45000,description:"Extra power for busy days, travel and unexpected outages.",availability:"Available",image:"https://images.unsplash.com/photo-1609592424566-4d4d9e1f1a41?auto=format&fit=crop&w=900&q=80",specifications:{Capacity:"10,000mAh",Ports:"USB / USB-C",Use:"Portable"}},
  {id:"wireless-earbuds",name:"Wireless Earbuds",category:"Headsets & Earphones",price:70000,description:"Everyday wireless sound for calls, music and podcasts.",availability:"Available",image:"https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?auto=format&fit=crop&w=900&q=80",specifications:{Connection:"Bluetooth",Case:"Charging case",Use:"Music & calls"}},
  {id:"portable-hard-drive",name:"Portable Hard Drive",category:"Hard Drives",price:160000,description:"Keep your important files backed up and close at hand.",availability:"Available",image:"https://images.unsplash.com/photo-1531492746076-161ca9b9d12b?auto=format&fit=crop&w=900&q=80",specifications:{Capacity:"1TB",Connection:"USB 3.0",Type:"Portable"}},
  {id:"electric-hot-plate",name:"Electric Hot Plate",category:"Hot Plates",price:115000,description:"A compact cooking essential for home, office or student life.",availability:"Available",image:"https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=900&q=80",specifications:{Power:"2000W",Control:"Adjustable",Use:"Home & office"}},
  {id:"solar-lantern",name:"Solar Lantern",category:"Solar Lanterns",price:90000,description:"Bright, rechargeable light for home, travel and backup power.",availability:"Available",image:"https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=900&q=80",specifications:{Power:"Solar rechargeable",Light:"LED",Use:"Indoor & outdoor"}}
];
function formatMWK(value){return `K${Number(value).toLocaleString("en-US")}`;}
function whatsappLink(product){const text=`Hello Multivision Electronics & Investments, I am interested in ${product.name} listed at ${formatMWK(product.price)}. Is it still available?`;return `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(text)}`;}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[char]));}
function normaliseProduct(product,index){return {...product,id:product.id||`product-${index}`,price:Number(product.price||0),availability:product.availability||"Check availability",description:product.description||"Contact us for product details and current stock.",specifications:product.specifications||{Category:product.category||"Electronics"}};}
async function getProducts(){try{const remote=await fetchProductsFromApi();return remote?.map(normaliseProduct)||demoProducts;}catch(error){const message=document.getElementById("api-message");if(message){message.hidden=false;message.textContent="Product catalogue is temporarily unavailable. Showing sample products — please contact us on WhatsApp to confirm current stock."}return demoProducts;}}
function productCard(product){return `<article class="product-card"><a class="product-image" href="product.html?id=${encodeURIComponent(product.id)}"><img src="${escapeHtml(product.image)}" alt="${escapeHtml(product.name)}"><span class="availability">${escapeHtml(product.availability)}</span></a><div class="product-info"><span class="product-category">${escapeHtml(product.category)}</span><h3>${escapeHtml(product.name)}</h3><p class="product-description">${escapeHtml(product.description)}</p><div class="product-price">${formatMWK(product.price)}</div><div class="product-actions"><a class="details-link" href="product.html?id=${encodeURIComponent(product.id)}">View details</a><a class="enquire-link" href="${whatsappLink(product)}" target="_blank" rel="noopener">WhatsApp</a></div></div></article>`;}
async function initCatalogue(){const grid=document.getElementById("product-grid");if(!grid)return;const search=document.getElementById("product-search"),filter=document.getElementById("category-filter"),count=document.getElementById("product-count"),clear=document.getElementById("clear-filters"),empty=document.getElementById("no-products");const products=await getProducts();const categories=[...new Set(products.map(product=>product.category))].sort();categories.forEach(category=>{const option=document.createElement("option");option.value=category;option.textContent=category;filter.appendChild(option);});const params=new URLSearchParams(location.search);const initialCategory=params.get("category");if(initialCategory&&categories.includes(initialCategory))filter.value=initialCategory;function render(){const query=search.value.trim().toLowerCase(),category=filter.value;const visible=products.filter(product=>(category==="all"||product.category===category)&&(!query||`${product.name} ${product.category} ${product.description}`.toLowerCase().includes(query)));grid.innerHTML=visible.map(productCard).join("");empty.hidden=visible.length>0;count.textContent=`Showing ${visible.length} of ${products.length} products`;clear.hidden=!query&&category==="all";}search.addEventListener("input",render);filter.addEventListener("change",render);clear.addEventListener("click",()=>{search.value="";filter.value="all";render();});render();}
async function initProductDetail(){const root=document.getElementById("product-detail");if(!root)return;const products=await getProducts();const id=new URLSearchParams(location.search).get("id");const product=products.find(item=>item.id===id)||products[0];if(!product){root.innerHTML="<p>Product not found.</p>";return;}document.title=`${product.name} | Multivision Electronics`;root.innerHTML=`<div class="detail-layout"><div class="detail-image"><img src="${escapeHtml(product.image)}" alt="${escapeHtml(product.name)}"></div><div class="detail-copy"><span class="product-category">${escapeHtml(product.category)}</span><h1>${escapeHtml(product.name)}</h1><p class="product-price">${formatMWK(product.price)}</p><p class="product-description">${escapeHtml(product.description)}</p><div class="spec-list">${Object.entries(product.specifications||{}).map(([key,value])=>`<div><span>${escapeHtml(key)}</span><b>${escapeHtml(value)}</b></div>`).join("")}<div><span>Availability</span><b>${escapeHtml(product.availability)}</b></div></div><div class="button-row"><a class="button button-primary" href="${whatsappLink(product)}" target="_blank" rel="noopener">Enquire on WhatsApp ↗</a><a class="button button-ghost" href="tel:+265992282807">Call us</a></div></div></div>`;}